Feature/vdx 171 support v1.0.09 and v1.0.11 types
Sphereon-Opensource/OpenID4VCI pull request #35
Opened 2023-03-30 07:10 UTC by sksadjad

based on previous pr for vdx-171, this pr only contains changes related to types and therefore can be easily merged in develop.
the subsequent changes in the other files/types will come after:
- deleting similar types for other files in the common module
- refactoring other modules to use the newly introduces interfaces

p.s: the build error for this pr is related to the publish task

2023-03-30 07:21 UTC, sksadjad commented
@nklomp I've added a todo for removing abstract keyword from my types, but now I'm thinking to preserve to make people realize they shouldn't use them directly. what do you think?

2023-03-30 13:04 UTC, nklomp requested changes
Small name change

2023-03-30 13:42 UTC, sksadjad commented on packages/common/lib/types/v1_0_11.types.ts
> +export interface InnerCredentialOfferV1_0_11 {
changed `InnerCredentialOfferV1_0_11` to `CredentialOfferPayloadV1_0_11`

2023-03-31 09:23 UTC, nklomp approved these changes

2023-03-31 09:24 UTC, merged